### ISSUE TITLE
[bug] Notification Banner not appearing

### ISSUE THREAD

**Issue by MatthewJWoolleyViva** [PostHog/notification-bar-app#5]
I have an enabled plug-in in PostHog and `posthog.config.opt_in_site_apps = true` when checked in the console, but nothing is showing. It has worked previously with the same config. Is there any further debugging I can do?

**Comment by ericalli** [comment]
Having the same issue here, using `posthog-js/react` version `1.160.3`:

```
    <PostHogProvider
      apiKey="..."
      options={
        {
          opt_in_site_apps: true,
          ...
        }
      }
    >
```

Banner is not appearing, no console errors to report.

**Comment by mdanilakis** [comment]
Same issue here

**Comment by mariusandra** [comment]
Hey all, this should work now. Apologies for the disruption. 🙃

**Comment by ian-weir** [comment]
@mariusandra Still not appearing for me today. I did notice an error in the console log : `Uncaught SyntaxError: "" string literal contains an unescaped line break` with a link to the the JS code handling it and line/column of 22:16. Assuming I'm reading it correctly I think it points to where the style is defined in that code.

```
//vvvv line 22 vvvv
var style = "
        .notification-bar-container {
            min-height: 56px;
        }
        .notification-bar {
            width: 100%;
            min-height: 56px;
            line-height: 36px;
            font-size: 24px;
            color: ".concat(config.textColor || 'default', ";
            background: ").concat(config.backgroundColor || 'default', ";
            font-weight: normal;
            font-family: -apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", "Roboto", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
            text-align: center;
            position: ").concat(config.position === 'sticky' ? 'fixed' : 'absolute', ";
            left: 0;
            top: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            z-index: 9999999;
        }
        .notification-bar a {
            color: ").concat(config.linkColor || config.textColor || 'default', ";
        }
        .notification-bar p {
            margin: 0;
        }
        ").concat(config.cssOverride || '', "
    ");
```

**Comment by mariusandra** [comment]
All right, one more try: it should work now :)

**Comment by ian-weir** [comment]
Working for me now! Thank you :)

**Comment by MatthewJWoolleyViva** [comment]
Yup for me too. Thanks @mariusandra
